import { GB2312_CHARS } from './gb2312';
import { BIG5_CHARS } from './big5';
import { JIS_LEVEL1_CHARS, JIS_LEVEL2_CHARS, JOYO_KANJI } from './japanese_jis';
import { KSX1001_HANGUL } from './korean_ksx1001';

export interface CharBlock {
  id: string;
  name: string;
  type: 'range' | 'list';
  ranges?: [number, number][]; // [start, end] inclusive
  list?: string | string[];
  extraChars?: string[];
  total: number;
}

export const UNICODE_BLOCKS: CharBlock[] = [
  {
    id: 'basic-latin',
    name: '基本拉丁字母 (ASCII)',
    type: 'range',
    ranges: [[0x0000, 0x007F]],
    total: 128,
  },
  {
    id: 'latin-1-supplement',
    name: '拉丁字母-1 辅助',
    type: 'range',
    ranges: [[0x0080, 0x00FF]],
    total: 128,
  },
  {
    id: 'latin-extended-a',
    name: '拉丁字母扩展 A',
    type: 'range',
    ranges: [[0x0100, 0x017F]],
    total: 128,
  },
  {
    id: 'latin-extended-b',
    name: '拉丁字母扩展 B',
    type: 'range',
    ranges: [[0x0180, 0x024F]],
    total: 208,
  },
  {
    id: 'ipa-extensions',
    name: '国际音标扩展',
    type: 'range',
    ranges: [[0x0250, 0x02AF]],
    total: 96,
  },
  {
    id: 'spacing-modifier-letters',
    name: '占位修饰符号',
    type: 'range',
    ranges: [[0x02B0, 0x02FF]],
    total: 80,
  },
  {
    id: 'combining-diacritical-marks',
    name: '结合附加符号',
    type: 'range',
    ranges: [[0x0300, 0x036F]],
    total: 112,
  },
  {
    id: 'greek-and-coptic',
    name: '希腊字母及科普特字母',
    type: 'range',
    ranges: [[0x0370, 0x03FF]],
    total: 144,
  },
  {
    id: 'cyrillic',
    name: '西里尔字母',
    type: 'range',
    ranges: [[0x0400, 0x04FF]],
    total: 256,
  },
  {
    id: 'cyrillic-supplement',
    name: '西里尔字母辅助',
    type: 'range',
    ranges: [[0x0500, 0x052F]],
    total: 48,
  },
  {
    id: 'armenian',
    name: '亚美尼亚字母',
    type: 'range',
    ranges: [[0x0530, 0x058F]],
    total: 96,
  },
  {
    id: 'hebrew',
    name: '希伯来字母',
    type: 'range',
    ranges: [[0x0590, 0x05FF]],
    total: 112,
  },
  {
    id: 'arabic',
    name: '阿拉伯字母',
    type: 'range',
    ranges: [[0x0600, 0x06FF]],
    total: 256,
  },
  {
    id: 'syriac',
    name: '叙利亚字母',
    type: 'range',
    ranges: [[0x0700, 0x074F]],
    total: 80,
  },
  {
    id: 'arabic-supplement',
    name: '阿拉伯字母补充',
    type: 'range',
    ranges: [[0x0750, 0x077F]],
    total: 48,
  },
  {
    id: 'thaana',
    name: '它拿字母',
    type: 'range',
    ranges: [[0x0780, 0x07BF]],
    total: 64,
  },
  {
    id: 'nko',
    name: '西非书面语言',
    type: 'range',
    ranges: [[0x07C0, 0x07FF]],
    total: 64,
  },
  {
    id: 'samaritan',
    name: '撒马利亚字母',
    type: 'range',
    ranges: [[0x0800, 0x083F]],
    total: 64,
  },
  {
    id: 'mandaic',
    name: '曼达克字母',
    type: 'range',
    ranges: [[0x0840, 0x085F]],
    total: 32,
  },
  {
    id: 'syriac-supplement',
    name: '叙利亚字母补充',
    type: 'range',
    ranges: [[0x0860, 0x086F]],
    total: 16,
  },
  {
    id: 'arabic-extended-b',
    name: '阿拉伯字母扩展-B',
    type: 'range',
    ranges: [[0x0870, 0x089F]],
    total: 48,
  },
  {
    id: 'arabic-extended-a',
    name: '阿拉伯字母扩展-A',
    type: 'range',
    ranges: [[0x08A0, 0x08FF]],
    total: 96,
  },
  {
    id: 'devanagari',
    name: '天城文',
    type: 'range',
    ranges: [[0x0900, 0x097F]],
    total: 128,
  },
  {
    id: 'bengali',
    name: '孟加拉文',
    type: 'range',
    ranges: [[0x0980, 0x09FF]],
    total: 128,
  },
  {
    id: 'gurmukhi',
    name: '古木基文',
    type: 'range',
    ranges: [[0x0A00, 0x0A7F]],
    total: 128,
  },
  {
    id: 'gujarati',
    name: '古吉拉特文',
    type: 'range',
    ranges: [[0x0A80, 0x0AFF]],
    total: 128,
  },
  {
    id: 'oriya',
    name: '奥里亚文',
    type: 'range',
    ranges: [[0x0B00, 0x0B7F]],
    total: 128,
  },
  {
    id: 'tamil',
    name: '泰米尔文',
    type: 'range',
    ranges: [[0x0B80, 0x0BFF]],
    total: 128,
  },
  {
    id: 'telugu',
    name: '泰卢固文',
    type: 'range',
    ranges: [[0x0C00, 0x0C7F]],
    total: 128,
  },
  {
    id: 'kannada',
    name: '卡纳达文',
    type: 'range',
    ranges: [[0x0C80, 0x0CFF]],
    total: 128,
  },
  {
    id: 'malayalam',
    name: '马拉雅拉姆文',
    type: 'range',
    ranges: [[0x0D00, 0x0D7F]],
    total: 128,
  },
  {
    id: 'sinhala',
    name: '僧伽罗文',
    type: 'range',
    ranges: [[0x0D80, 0x0DFF]],
    total: 128,
  },
  {
    id: 'thai',
    name: '泰文字母',
    type: 'range',
    ranges: [[0x0E00, 0x0E7F]],
    total: 128,
  },
  {
    id: 'lao',
    name: '老挝文',
    type: 'range',
    ranges: [[0x0E80, 0x0EFF]],
    total: 128,
  },
  {
    id: 'tibetan',
    name: '藏文',
    type: 'range',
    ranges: [[0x0F00, 0x0FFF]],
    total: 256,
  },
  {
    id: 'myanmar',
    name: '缅甸文',
    type: 'range',
    ranges: [[0x1000, 0x109F]],
    total: 160,
  },
  {
    id: 'georgian',
    name: '格鲁吉亚字母',
    type: 'range',
    ranges: [[0x10A0, 0x10FF]],
    total: 96,
  },
  {
    id: 'hangul-jamo',
    name: '谚文字母',
    type: 'range',
    ranges: [[0x1100, 0x11FF]],
    total: 256,
  },
  {
    id: 'ethiopic',
    name: '埃塞俄比亚字母',
    type: 'range',
    ranges: [[0x1200, 0x137F]],
    total: 384,
  },
  {
    id: 'ethiopic-supplement',
    name: '埃塞俄比亚字母补充',
    type: 'range',
    ranges: [[0x1380, 0x139F]],
    total: 32,
  },
  {
    id: 'cherokee',
    name: '切罗基文',
    type: 'range',
    ranges: [[0x13A0, 0x13FF]],
    total: 96,
  },
  {
    id: 'unified-canadian-aboriginal-syllabics',
    name: '统一加拿大原住民音节文字',
    type: 'range',
    ranges: [[0x1400, 0x167F]],
    total: 640,
  },
  {
    id: 'ogham',
    name: '欧甘字母',
    type: 'range',
    ranges: [[0x1680, 0x169F]],
    total: 32,
  },
  {
    id: 'runic',
    name: '卢恩字母',
    type: 'range',
    ranges: [[0x16A0, 0x16FF]],
    total: 96,
  },
  {
    id: 'tagalog',
    name: '他加禄字母',
    type: 'range',
    ranges: [[0x1700, 0x171F]],
    total: 32,
  },
  {
    id: 'hanunoo',
    name: '哈努诺文',
    type: 'range',
    ranges: [[0x1720, 0x173F]],
    total: 32,
  },
  {
    id: 'buhid',
    name: '布希德字母',
    type: 'range',
    ranges: [[0x1740, 0x175F]],
    total: 32,
  },
  {
    id: 'tagbanwa',
    name: '塔格班瓦字母',
    type: 'range',
    ranges: [[0x1760, 0x177F]],
    total: 32,
  },
  {
    id: 'khmer',
    name: '高棉文',
    type: 'range',
    ranges: [[0x1780, 0x17FF]],
    total: 128,
  },
  {
    id: 'mongolian',
    name: '蒙古文',
    type: 'range',
    ranges: [[0x1800, 0x18AF]],
    total: 176,
  },
  {
    id: 'unified-canadian-aboriginal-syllabics-extended',
    name: '统一加拿大原住民音节文字扩展',
    type: 'range',
    ranges: [[0x18B0, 0x18FF]],
    total: 80,
  },
  {
    id: 'limbu',
    name: '林布文',
    type: 'range',
    ranges: [[0x1900, 0x194F]],
    total: 80,
  },
  {
    id: 'tai-le',
    name: '傣那文',
    type: 'range',
    ranges: [[0x1950, 0x197F]],
    total: 48,
  },
  {
    id: 'new-tai-lue',
    name: '新傣仂文',
    type: 'range',
    ranges: [[0x1980, 0x19DF]],
    total: 96,
  },
  {
    id: 'khmer-symbols',
    name: '高棉文符号',
    type: 'range',
    ranges: [[0x19E0, 0x19FF]],
    total: 32,
  },
  {
    id: 'buginese',
    name: '布吉字母',
    type: 'range',
    ranges: [[0x1A00, 0x1A1F]],
    total: 32,
  },
  {
    id: 'tai-tham',
    name: '老傣仂文',
    type: 'range',
    ranges: [[0x1A20, 0x1AAF]],
    total: 144,
  },
  {
    id: 'combining-diacritical-marks-extended',
    name: '结合附加符号扩展',
    type: 'range',
    ranges: [[0x1AB0, 0x1AFF]],
    total: 80,
  },
  {
    id: 'balinese',
    name: '巴厘字母',
    type: 'range',
    ranges: [[0x1B00, 0x1B7F]],
    total: 128,
  },
  {
    id: 'sundanese',
    name: '巽他字母',
    type: 'range',
    ranges: [[0x1B80, 0x1BBF]],
    total: 64,
  },
  {
    id: 'batak',
    name: '巴塔克文',
    type: 'range',
    ranges: [[0x1BC0, 0x1BFF]],
    total: 64,
  },
  {
    id: 'lepcha',
    name: '绒巴文',
    type: 'range',
    ranges: [[0x1C00, 0x1C4F]],
    total: 80,
  },
  {
    id: 'ol-chiki',
    name: '桑塔利文',
    type: 'range',
    ranges: [[0x1C50, 0x1C7F]],
    total: 48,
  },
  {
    id: 'cyrillic-extended-c',
    name: '西里尔字母扩展-C',
    type: 'range',
    ranges: [[0x1C80, 0x1C8F]],
    total: 16,
  },
  {
    id: 'georgian-extended',
    name: '格鲁吉亚字母扩展',
    type: 'range',
    ranges: [[0x1C90, 0x1CBF]],
    total: 48,
  },
  {
    id: 'sundanese-supplement',
    name: '巽他字母补充',
    type: 'range',
    ranges: [[0x1CC0, 0x1CCF]],
    total: 16,
  },
  {
    id: 'vedic-extensions',
    name: '吠陀扩展',
    type: 'range',
    ranges: [[0x1CD0, 0x1CFF]],
    total: 48,
  },
  {
    id: 'phonetic-extensions',
    name: '音标扩展',
    type: 'range',
    ranges: [[0x1D00, 0x1D7F]],
    total: 128,
  },
  {
    id: 'phonetic-extensions-supplement',
    name: '音标扩展补充',
    type: 'range',
    ranges: [[0x1D80, 0x1DBF]],
    total: 64,
  },
  {
    id: 'combining-diacritical-marks-supplement',
    name: '结合附加符号补充',
    type: 'range',
    ranges: [[0x1DC0, 0x1DFF]],
    total: 64,
  },
  {
    id: 'latin-extended-additional',
    name: '拉丁字母扩展附加',
    type: 'range',
    ranges: [[0x1E00, 0x1EFF]],
    total: 256,
  },
  {
    id: 'greek-extended',
    name: '希腊字母扩展',
    type: 'range',
    ranges: [[0x1F00, 0x1FFF]],
    total: 256,
  },
  {
    id: 'general-punctuation',
    name: '一般标点',
    type: 'range',
    ranges: [[0x2000, 0x206F]],
    total: 112,
  },
  {
    id: 'superscripts-and-subscripts',
    name: '上标和下标',
    type: 'range',
    ranges: [[0x2070, 0x209F]],
    total: 48,
  },
  {
    id: 'currency-symbols',
    name: '货币符号',
    type: 'range',
    ranges: [[0x20A0, 0x20CF]],
    total: 48,
  },
  {
    id: 'combining-diacritical-marks-for-symbols',
    name: '符号用结合附加符号',
    type: 'range',
    ranges: [[0x20D0, 0x20FF]],
    total: 48,
  },
  {
    id: 'letterlike-symbols',
    name: '类字母符号',
    type: 'range',
    ranges: [[0x2100, 0x214F]],
    total: 80,
  },
  {
    id: 'number-forms',
    name: '数字形式',
    type: 'range',
    ranges: [[0x2150, 0x218F]],
    total: 64,
  },
  {
    id: 'arrows',
    name: '箭头',
    type: 'range',
    ranges: [[0x2190, 0x21FF]],
    total: 112,
  },
  {
    id: 'mathematical-operators',
    name: '数学运算符',
    type: 'range',
    ranges: [[0x2200, 0x22FF]],
    total: 256,
  },
  {
    id: 'miscellaneous-technical',
    name: '杂项工业符号',
    type: 'range',
    ranges: [[0x2300, 0x23FF]],
    total: 256,
  },
  {
    id: 'control-pictures',
    name: '控制图形',
    type: 'range',
    ranges: [[0x2400, 0x243F]],
    total: 64,
  },
  {
    id: 'optical-character-recognition',
    name: '光学字符识别',
    type: 'range',
    ranges: [[0x2440, 0x245F]],
    total: 32,
  },
  {
    id: 'enclosed-alphanumerics',
    name: '带圈字母数字',
    type: 'range',
    ranges: [[0x2460, 0x24FF]],
    total: 160,
  },
  {
    id: 'box-drawing',
    name: '制表符',
    type: 'range',
    ranges: [[0x2500, 0x257F]],
    total: 128,
  },
  {
    id: 'block-elements',
    name: '方块元素',
    type: 'range',
    ranges: [[0x2580, 0x259F]],
    total: 32,
  },
  {
    id: 'geometric-shapes',
    name: '几何图形',
    type: 'range',
    ranges: [[0x25A0, 0x25FF]],
    total: 96,
  },
  {
    id: 'miscellaneous-symbols',
    name: '杂项符号',
    type: 'range',
    ranges: [[0x2600, 0x26FF]],
    total: 256,
  },
  {
    id: 'dingbats',
    name: '装饰符号',
    type: 'range',
    ranges: [[0x2700, 0x27BF]],
    total: 192,
  },
  {
    id: 'miscellaneous-mathematical-symbols-a',
    name: '杂项数学符号-A',
    type: 'range',
    ranges: [[0x27C0, 0x27EF]],
    total: 48,
  },
  {
    id: 'supplemental-arrows-a',
    name: '补充箭头-A',
    type: 'range',
    ranges: [[0x27F0, 0x27FF]],
    total: 16,
  },
  {
    id: 'braille-patterns',
    name: '盲文图案',
    type: 'range',
    ranges: [[0x2800, 0x28FF]],
    total: 256,
  },
  {
    id: 'supplemental-arrows-b',
    name: '补充箭头-B',
    type: 'range',
    ranges: [[0x2900, 0x297F]],
    total: 128,
  },
  {
    id: 'miscellaneous-mathematical-symbols-b',
    name: '杂项数学符号-B',
    type: 'range',
    ranges: [[0x2980, 0x29FF]],
    total: 128,
  },
  {
    id: 'supplemental-mathematical-operators',
    name: '补充数学运算符',
    type: 'range',
    ranges: [[0x2A00, 0x2AFF]],
    total: 256,
  },
  {
    id: 'miscellaneous-symbols-and-arrows',
    name: '杂项符号和箭头',
    type: 'range',
    ranges: [[0x2B00, 0x2BFF]],
    total: 256,
  },
  {
    id: 'glagolitic',
    name: '格拉哥里字母',
    type: 'range',
    ranges: [[0x2C00, 0x2C5F]],
    total: 96,
  },
  {
    id: 'latin-extended-c',
    name: '拉丁字母扩展-C',
    type: 'range',
    ranges: [[0x2C60, 0x2C7F]],
    total: 32,
  },
  {
    id: 'coptic',
    name: '科普特字母',
    type: 'range',
    ranges: [[0x2C80, 0x2CFF]],
    total: 128,
  },
  {
    id: 'georgian-supplement',
    name: '格鲁吉亚字母补充',
    type: 'range',
    ranges: [[0x2D00, 0x2D2F]],
    total: 48,
  },
  {
    id: 'tifinagh',
    name: '提非纳文',
    type: 'range',
    ranges: [[0x2D30, 0x2D7F]],
    total: 80,
  },
  {
    id: 'ethiopic-extended',
    name: '埃塞俄比亚字母扩展',
    type: 'range',
    ranges: [[0x2D80, 0x2DDF]],
    total: 96,
  },
  {
    id: 'cyrillic-extended-a',
    name: '西里尔字母扩展-A',
    type: 'range',
    ranges: [[0x2DE0, 0x2DFF]],
    total: 32,
  },
  {
    id: 'supplemental-punctuation',
    name: '补充标点',
    type: 'range',
    ranges: [[0x2E00, 0x2E7F]],
    total: 128,
  },
  {
    id: 'cjk-radicals-supplement',
    name: '中日韩汉字部首补充',
    type: 'range',
    ranges: [[0x2E80, 0x2EFF]],
    total: 128,
  },
  {
    id: 'kangxi-radicals',
    name: '康熙部首',
    type: 'range',
    ranges: [[0x2F00, 0x2FDF]],
    total: 224,
  },
  {
    id: 'ideographic-description-characters',
    name: '表意文字描述字符',
    type: 'range',
    ranges: [[0x2FF0, 0x2FFF]],
    total: 16,
  },
  {
    id: 'cjk-symbols-and-punctuation',
    name: '中日韩符号和标点',
    type: 'range',
    ranges: [[0x3000, 0x303F]],
    total: 64,
  },
  {
    id: 'hiragana',
    name: '平假名',
    type: 'range',
    ranges: [[0x3040, 0x309F]],
    total: 96,
  },
  {
    id: 'katakana',
    name: '片假名',
    type: 'range',
    ranges: [[0x30A0, 0x30FF]],
    total: 96,
  },
  {
    id: 'bopomofo',
    name: '注音符号',
    type: 'range',
    ranges: [[0x3100, 0x312F]],
    total: 48,
  },
  {
    id: 'hangul-compatibility-jamo',
    name: '谚文兼容字母',
    type: 'range',
    ranges: [[0x3130, 0x318F]],
    total: 96,
  },
  {
    id: 'kanbun',
    name: '汉文训读符号',
    type: 'range',
    ranges: [[0x3190, 0x319F]],
    total: 16,
  },
  {
    id: 'bopomofo-extended',
    name: '注音符号扩展',
    type: 'range',
    ranges: [[0x31A0, 0x31BF]],
    total: 32,
  },
  {
    id: 'cjk-strokes',
    name: '中日韩笔画',
    type: 'range',
    ranges: [[0x31C0, 0x31EF]],
    total: 48,
  },
  {
    id: 'katakana-phonetic-extensions',
    name: '片假名音标扩展',
    type: 'range',
    ranges: [[0x31F0, 0x31FF]],
    total: 16,
  },
  {
    id: 'enclosed-cjk-letters-and-months',
    name: 'Enclosed CJK Letters and Months',
    type: 'range',
    ranges: [[0x3200, 0x32FF]],
    total: 256,
  },
  {
    id: 'cjk-compatibility',
    name: '中日韩兼容字符',
    type: 'range',
    ranges: [[0x3300, 0x33FF]],
    total: 256,
  },
  {
    id: 'cjk-unified-ideographs-extension-a',
    name: 'CJK 扩展 A 区',
    type: 'range',
    ranges: [[0x3400, 0x4DBF]],
    total: 6592,
  },
  {
    id: 'yijing-hexagram-symbols',
    name: '易经六十四卦符号',
    type: 'range',
    ranges: [[0x4DC0, 0x4DFF]],
    total: 64,
  },
  {
    id: 'cjk-unified-ideographs',
    name: 'CJK 基本区',
    type: 'range',
    ranges: [[0x4E00, 0x9FFF]],
    total: 20992,
  },
  {
    id: 'yi-syllables',
    name: '彝文音节',
    type: 'range',
    ranges: [[0xA000, 0xA48F]],
    total: 1168,
  },
  {
    id: 'yi-radicals',
    name: '彝文部首',
    type: 'range',
    ranges: [[0xA490, 0xA4CF]],
    total: 64,
  },
  {
    id: 'lisu',
    name: '老傈僳文',
    type: 'range',
    ranges: [[0xA4D0, 0xA4FF]],
    total: 48,
  },
  {
    id: 'vai',
    name: '瓦伊文',
    type: 'range',
    ranges: [[0xA500, 0xA63F]],
    total: 320,
  },
  {
    id: 'cyrillic-extended-b',
    name: '西里尔字母扩展-B',
    type: 'range',
    ranges: [[0xA640, 0xA69F]],
    total: 96,
  },
  {
    id: 'bamum',
    name: '巴穆姆文',
    type: 'range',
    ranges: [[0xA6A0, 0xA6FF]],
    total: 96,
  },
  {
    id: 'modifier-tone-letters',
    name: '声调修饰字母',
    type: 'range',
    ranges: [[0xA700, 0xA71F]],
    total: 32,
  },
  {
    id: 'latin-extended-d',
    name: '拉丁字母扩展-D',
    type: 'range',
    ranges: [[0xA720, 0xA7FF]],
    total: 224,
  },
  {
    id: 'syloti-nagri',
    name: '锡尔赫特文',
    type: 'range',
    ranges: [[0xA800, 0xA82F]],
    total: 48,
  },
  {
    id: 'common-indic-number-forms',
    name: '通用印度数字格式',
    type: 'range',
    ranges: [[0xA830, 0xA83F]],
    total: 16,
  },
  {
    id: 'phags-pa',
    name: '八思巴文',
    type: 'range',
    ranges: [[0xA840, 0xA87F]],
    total: 64,
  },
  {
    id: 'saurashtra',
    name: '索拉什特拉文',
    type: 'range',
    ranges: [[0xA880, 0xA8DF]],
    total: 96,
  },
  {
    id: 'devanagari-extended',
    name: '天城文扩展',
    type: 'range',
    ranges: [[0xA8E0, 0xA8FF]],
    total: 32,
  },
  {
    id: 'kayah-li',
    name: '克耶字母',
    type: 'range',
    ranges: [[0xA900, 0xA92F]],
    total: 48,
  },
  {
    id: 'rejang',
    name: '勒姜字母',
    type: 'range',
    ranges: [[0xA930, 0xA95F]],
    total: 48,
  },
  {
    id: 'hangul-jamo-extended-a',
    name: '谚文字母扩展-A',
    type: 'range',
    ranges: [[0xA960, 0xA97F]],
    total: 32,
  },
  {
    id: 'javanese',
    name: '爪哇字母',
    type: 'range',
    ranges: [[0xA980, 0xA9DF]],
    total: 96,
  },
  {
    id: 'myanmar-extended-b',
    name: '缅甸文扩展-B',
    type: 'range',
    ranges: [[0xA9E0, 0xA9FF]],
    total: 32,
  },
  {
    id: 'cham',
    name: '占文',
    type: 'range',
    ranges: [[0xAA00, 0xAA5F]],
    total: 96,
  },
  {
    id: 'myanmar-extended-a',
    name: '缅甸文扩展-A',
    type: 'range',
    ranges: [[0xAA60, 0xAA7F]],
    total: 32,
  },
  {
    id: 'tai-viet',
    name: '傣越文',
    type: 'range',
    ranges: [[0xAA80, 0xAADF]],
    total: 96,
  },
  {
    id: 'meetei-mayek-extensions',
    name: '梅泰文扩展',
    type: 'range',
    ranges: [[0xAAE0, 0xAAFF]],
    total: 32,
  },
  {
    id: 'ethiopic-extended-a',
    name: '埃塞俄比亚字母扩展-A',
    type: 'range',
    ranges: [[0xAB00, 0xAB2F]],
    total: 48,
  },
  {
    id: 'latin-extended-e',
    name: '拉丁字母扩展-E',
    type: 'range',
    ranges: [[0xAB30, 0xAB6F]],
    total: 64,
  },
  {
    id: 'cherokee-supplement',
    name: '切罗基文补充',
    type: 'range',
    ranges: [[0xAB70, 0xABBF]],
    total: 80,
  },
  {
    id: 'meetei-mayek',
    name: '曼尼普尔文',
    type: 'range',
    ranges: [[0xABC0, 0xABFF]],
    total: 64,
  },
  {
    id: 'hangul-syllables',
    name: '谚文音节',
    type: 'range',
    ranges: [[0xAC00, 0xD7AF]],
    total: 11184,
  },
  {
    id: 'hangul-jamo-extended-b',
    name: '谚文字母扩展-B',
    type: 'range',
    ranges: [[0xD7B0, 0xD7FF]],
    total: 80,
  },
  {
    id: 'high-surrogates',
    name: 'UTF-16的高半代用区',
    type: 'range',
    ranges: [[0xD800, 0xDB7F]],
    total: 896,
  },
  {
    id: 'high-private-use-surrogates',
    name: 'UTF-16的高半私人代用区',
    type: 'range',
    ranges: [[0xDB80, 0xDBFF]],
    total: 128,
  },
  {
    id: 'low-surrogates',
    name: 'UTF-16的低半代用区',
    type: 'range',
    ranges: [[0xDC00, 0xDFFF]],
    total: 1024,
  },
  {
    id: 'private-use-area',
    name: '私用区',
    type: 'range',
    ranges: [[0xE000, 0xF8FF]],
    total: 6400,
  },
  {
    id: 'cjk-compatibility-ideographs',
    name: '中日韩兼容表意文字',
    type: 'range',
    ranges: [[0xF900, 0xFAFF]],
    total: 512,
  },
  {
    id: 'alphabetic-presentation-forms',
    name: '字母表达形式',
    type: 'range',
    ranges: [[0xFB00, 0xFB4F]],
    total: 80,
  },
  {
    id: 'arabic-presentation-forms-a',
    name: '阿拉伯字母表达形式-A',
    type: 'range',
    ranges: [[0xFB50, 0xFDFF]],
    total: 688,
  },
  {
    id: 'variation-selectors',
    name: '变体选择符',
    type: 'range',
    ranges: [[0xFE00, 0xFE0F]],
    total: 16,
  },
  {
    id: 'vertical-forms',
    name: '竖排形式',
    type: 'range',
    ranges: [[0xFE10, 0xFE1F]],
    total: 16,
  },
  {
    id: 'combining-half-marks',
    name: '组合半符号',
    type: 'range',
    ranges: [[0xFE20, 0xFE2F]],
    total: 16,
  },
  {
    id: 'cjk-compatibility-forms',
    name: '中日韩兼容形式',
    type: 'range',
    ranges: [[0xFE30, 0xFE4F]],
    total: 32,
  },
  {
    id: 'small-form-variants',
    name: '小写变体形式',
    type: 'range',
    ranges: [[0xFE50, 0xFE6F]],
    total: 32,
  },
  {
    id: 'arabic-presentation-forms-b',
    name: '阿拉伯字母表达形式-B',
    type: 'range',
    ranges: [[0xFE70, 0xFEFF]],
    total: 144,
  },
  {
    id: 'halfwidth-and-fullwidth-forms',
    name: '半角和全角形式',
    type: 'range',
    ranges: [[0xFF00, 0xFFEF]],
    total: 240,
  },
  {
    id: 'specials',
    name: '特殊字符',
    type: 'range',
    ranges: [[0xFFF0, 0xFFFF]],
    total: 16,
  },
  {
    id: 'linear-b-syllabary',
    name: '线形文字B音节文字',
    type: 'range',
    ranges: [[0x10000, 0x1007F]],
    total: 128,
  },
  {
    id: 'linear-b-ideograms',
    name: '线形文字B表意文字',
    type: 'range',
    ranges: [[0x10080, 0x100FF]],
    total: 128,
  },
  {
    id: 'aegean-numbers',
    name: '爱琴数字',
    type: 'range',
    ranges: [[0x10100, 0x1013F]],
    total: 64,
  },
  {
    id: 'ancient-greek-numbers',
    name: '古希腊数字',
    type: 'range',
    ranges: [[0x10140, 0x1018F]],
    total: 80,
  },
  {
    id: 'ancient-symbols',
    name: '古代符号',
    type: 'range',
    ranges: [[0x10190, 0x101CF]],
    total: 64,
  },
  {
    id: 'phaistos-disc',
    name: '斐斯托斯圆盘',
    type: 'range',
    ranges: [[0x101D0, 0x101FF]],
    total: 48,
  },
  {
    id: 'lycian',
    name: '吕基亚字母',
    type: 'range',
    ranges: [[0x10280, 0x1029F]],
    total: 32,
  },
  {
    id: 'carian',
    name: '卡利亚字母',
    type: 'range',
    ranges: [[0x102A0, 0x102DF]],
    total: 64,
  },
  {
    id: 'coptic-epact-numbers',
    name: '科普特闰余数字',
    type: 'range',
    ranges: [[0x102E0, 0x102FF]],
    total: 32,
  },
  {
    id: 'old-italic',
    name: '古意大利字母',
    type: 'range',
    ranges: [[0x10300, 0x1032F]],
    total: 48,
  },
  {
    id: 'gothic',
    name: '哥特字母',
    type: 'range',
    ranges: [[0x10330, 0x1034F]],
    total: 32,
  },
  {
    id: 'old-permic',
    name: '古彼尔姆文',
    type: 'range',
    ranges: [[0x10350, 0x1037F]],
    total: 48,
  },
  {
    id: 'ugaritic',
    name: '乌加里特字母',
    type: 'range',
    ranges: [[0x10380, 0x1039F]],
    total: 32,
  },
  {
    id: 'old-persian',
    name: '古波斯楔形文字',
    type: 'range',
    ranges: [[0x103A0, 0x103DF]],
    total: 64,
  },
  {
    id: 'deseret',
    name: '德赛雷特字母',
    type: 'range',
    ranges: [[0x10400, 0x1044F]],
    total: 80,
  },
  {
    id: 'shavian',
    name: '萧伯纳字母',
    type: 'range',
    ranges: [[0x10450, 0x1047F]],
    total: 48,
  },
  {
    id: 'osmanya',
    name: '奥斯曼亚字母',
    type: 'range',
    ranges: [[0x10480, 0x104AF]],
    total: 48,
  },
  {
    id: 'osage',
    name: '欧塞奇字母',
    type: 'range',
    ranges: [[0x104B0, 0x104FF]],
    total: 80,
  },
  {
    id: 'elbasan',
    name: '爱尔巴桑字母',
    type: 'range',
    ranges: [[0x10500, 0x1052F]],
    total: 48,
  },
  {
    id: 'caucasian-albanian',
    name: '高加索阿尔巴尼亚文',
    type: 'range',
    ranges: [[0x10530, 0x1056F]],
    total: 64,
  },
  {
    id: 'vithkuqi',
    name: '维斯库奇字母',
    type: 'range',
    ranges: [[0x10570, 0x105BF]],
    total: 80,
  },
  {
    id: 'todhri',
    name: '托特里文',
    type: 'range',
    ranges: [[0x105C0, 0x105FF]],
    total: 64,
  },
  {
    id: 'linear-a',
    name: '线形文字A',
    type: 'range',
    ranges: [[0x10600, 0x1077F]],
    total: 384,
  },
  {
    id: 'latin-extended-f',
    name: '拉丁字母扩展-F',
    type: 'range',
    ranges: [[0x10780, 0x107BF]],
    total: 64,
  },
  {
    id: 'cypriot-syllabary',
    name: '塞浦路斯音节文字',
    type: 'range',
    ranges: [[0x10800, 0x1083F]],
    total: 64,
  },
  {
    id: 'imperial-aramaic',
    name: '阿拉姆字母',
    type: 'range',
    ranges: [[0x10840, 0x1085F]],
    total: 32,
  },
  {
    id: 'palmyrene',
    name: '巴尔米拉字母',
    type: 'range',
    ranges: [[0x10860, 0x1087F]],
    total: 32,
  },
  {
    id: 'nabataean',
    name: '纳巴泰字母',
    type: 'range',
    ranges: [[0x10880, 0x108AF]],
    total: 48,
  },
  {
    id: 'hatran',
    name: '哈特拉文',
    type: 'range',
    ranges: [[0x108E0, 0x108FF]],
    total: 32,
  },
  {
    id: 'phoenician',
    name: '腓尼基字母',
    type: 'range',
    ranges: [[0x10900, 0x1091F]],
    total: 32,
  },
  {
    id: 'lydian',
    name: '吕底亚字母',
    type: 'range',
    ranges: [[0x10920, 0x1093F]],
    total: 32,
  },
  {
    id: 'sidetic',
    name: '锡德文',
    type: 'range',
    ranges: [[0x10940, 0x1095F]],
    total: 32,
  },
  {
    id: 'meroitic-hieroglyphs',
    name: '麦罗埃文圣书体',
    type: 'range',
    ranges: [[0x10980, 0x1099F]],
    total: 32,
  },
  {
    id: 'meroitic-cursive',
    name: '麦罗埃文草书体',
    type: 'range',
    ranges: [[0x109A0, 0x109FF]],
    total: 96,
  },
  {
    id: 'kharoshthi',
    name: '佉卢文',
    type: 'range',
    ranges: [[0x10A00, 0x10A5F]],
    total: 96,
  },
  {
    id: 'old-south-arabian',
    name: '古南阿拉伯字母',
    type: 'range',
    ranges: [[0x10A60, 0x10A7F]],
    total: 32,
  },
  {
    id: 'old-north-arabian',
    name: '古北阿拉伯字母',
    type: 'range',
    ranges: [[0x10A80, 0x10A9F]],
    total: 32,
  },
  {
    id: 'manichaean',
    name: '摩尼字母',
    type: 'range',
    ranges: [[0x10AC0, 0x10AFF]],
    total: 64,
  },
  {
    id: 'avestan',
    name: '阿维斯陀字母',
    type: 'range',
    ranges: [[0x10B00, 0x10B3F]],
    total: 64,
  },
  {
    id: 'inscriptional-parthian',
    name: '碑刻帕提亚文',
    type: 'range',
    ranges: [[0x10B40, 0x10B5F]],
    total: 32,
  },
  {
    id: 'inscriptional-pahlavi',
    name: '碑刻巴列维文',
    type: 'range',
    ranges: [[0x10B60, 0x10B7F]],
    total: 32,
  },
  {
    id: 'psalter-pahlavi',
    name: '诗篇巴列维文',
    type: 'range',
    ranges: [[0x10B80, 0x10BAF]],
    total: 48,
  },
  {
    id: 'old-turkic',
    name: '古突厥文',
    type: 'range',
    ranges: [[0x10C00, 0x10C4F]],
    total: 80,
  },
  {
    id: 'old-hungarian',
    name: '古匈牙利字母',
    type: 'range',
    ranges: [[0x10C80, 0x10CFF]],
    total: 128,
  },
  {
    id: 'hanifi-rohingya',
    name: '哈尼菲罗兴亚文',
    type: 'range',
    ranges: [[0x10D00, 0x10D3F]],
    total: 64,
  },
  {
    id: 'garay',
    name: '加雷字母',
    type: 'range',
    ranges: [[0x10D40, 0x10D8F]],
    total: 80,
  },
  {
    id: 'rumi-numeral-symbols',
    name: '卢米文数字',
    type: 'range',
    ranges: [[0x10E60, 0x10E7F]],
    total: 32,
  },
  {
    id: 'yezidi',
    name: '雅兹迪文',
    type: 'range',
    ranges: [[0x10E80, 0x10EBF]],
    total: 64,
  },
  {
    id: 'arabic-extended-c',
    name: '阿拉伯字母扩展-C',
    type: 'range',
    ranges: [[0x10EC0, 0x10EFF]],
    total: 64,
  },
  {
    id: 'old-sogdian',
    name: '古粟特字母',
    type: 'range',
    ranges: [[0x10F00, 0x10F2F]],
    total: 48,
  },
  {
    id: 'sogdian',
    name: '粟特字母',
    type: 'range',
    ranges: [[0x10F30, 0x10F6F]],
    total: 64,
  },
  {
    id: 'old-uyghur',
    name: '回鹘文',
    type: 'range',
    ranges: [[0x10F70, 0x10FAF]],
    total: 64,
  },
  {
    id: 'chorasmian',
    name: '花剌子模字母',
    type: 'range',
    ranges: [[0x10FB0, 0x10FDF]],
    total: 48,
  },
  {
    id: 'elymaic',
    name: '埃利迈文',
    type: 'range',
    ranges: [[0x10FE0, 0x10FFF]],
    total: 32,
  },
  {
    id: 'brahmi',
    name: '婆罗米文',
    type: 'range',
    ranges: [[0x11000, 0x1107F]],
    total: 128,
  },
  {
    id: 'kaithi',
    name: '凯提文',
    type: 'range',
    ranges: [[0x11080, 0x110CF]],
    total: 80,
  },
  {
    id: 'sora-sompeng',
    name: '索拉僧平文',
    type: 'range',
    ranges: [[0x110D0, 0x110FF]],
    total: 48,
  },
  {
    id: 'chakma',
    name: '查克玛文',
    type: 'range',
    ranges: [[0x11100, 0x1114F]],
    total: 80,
  },
  {
    id: 'mahajani',
    name: '马哈贾尼文',
    type: 'range',
    ranges: [[0x11150, 0x1117F]],
    total: 48,
  },
  {
    id: 'sharada',
    name: '夏拉达文',
    type: 'range',
    ranges: [[0x11180, 0x111DF]],
    total: 96,
  },
  {
    id: 'sinhala-archaic-numbers',
    name: '古僧伽罗文数字',
    type: 'range',
    ranges: [[0x111E0, 0x111FF]],
    total: 32,
  },
  {
    id: 'khojki',
    name: '可吉文',
    type: 'range',
    ranges: [[0x11200, 0x1124F]],
    total: 80,
  },
  {
    id: 'multani',
    name: '穆尔塔尼文',
    type: 'range',
    ranges: [[0x11280, 0x112AF]],
    total: 48,
  },
  {
    id: 'khudawadi',
    name: '库达瓦迪文',
    type: 'range',
    ranges: [[0x112B0, 0x112FF]],
    total: 80,
  },
  {
    id: 'grantha',
    name: '古兰塔文',
    type: 'range',
    ranges: [[0x11300, 0x1137F]],
    total: 128,
  },
  {
    id: 'tulu-tigalari',
    name: '图卢文',
    type: 'range',
    ranges: [[0x11380, 0x113FF]],
    total: 128,
  },
  {
    id: 'newa',
    name: '尼瓦尔文',
    type: 'range',
    ranges: [[0x11400, 0x1147F]],
    total: 128,
  },
  {
    id: 'tirhuta',
    name: '底罗仆多文',
    type: 'range',
    ranges: [[0x11480, 0x114DF]],
    total: 96,
  },
  {
    id: 'siddham',
    name: '悉昙文',
    type: 'range',
    ranges: [[0x11580, 0x115FF]],
    total: 128,
  },
  {
    id: 'modi',
    name: '莫迪文',
    type: 'range',
    ranges: [[0x11600, 0x1165F]],
    total: 96,
  },
  {
    id: 'mongolian-supplement',
    name: '蒙古文补充',
    type: 'range',
    ranges: [[0x11660, 0x1167F]],
    total: 32,
  },
  {
    id: 'takri',
    name: '塔克里字母',
    type: 'range',
    ranges: [[0x11680, 0x116CF]],
    total: 80,
  },
  {
    id: 'myanmar-extended-c',
    name: '缅甸文扩展-C',
    type: 'range',
    ranges: [[0x116D0, 0x116FF]],
    total: 48,
  },
  {
    id: 'ahom',
    name: '阿洪姆文',
    type: 'range',
    ranges: [[0x11700, 0x1174F]],
    total: 80,
  },
  {
    id: 'dogra',
    name: '多格拉文',
    type: 'range',
    ranges: [[0x11800, 0x1184F]],
    total: 80,
  },
  {
    id: 'warang-citi',
    name: '瓦兰齐地文',
    type: 'range',
    ranges: [[0x118A0, 0x118FF]],
    total: 96,
  },
  {
    id: 'dives-akuru',
    name: '岛屿字母',
    type: 'range',
    ranges: [[0x11900, 0x1195F]],
    total: 96,
  },
  {
    id: 'nandinagari',
    name: '南迪城文',
    type: 'range',
    ranges: [[0x119A0, 0x119FF]],
    total: 96,
  },
  {
    id: 'zanabazar-square',
    name: '札那巴札尔方形字母',
    type: 'range',
    ranges: [[0x11A00, 0x11A4F]],
    total: 80,
  },
  {
    id: 'soyombo',
    name: '索永布字母',
    type: 'range',
    ranges: [[0x11A50, 0x11AAF]],
    total: 96,
  },
  {
    id: 'unified-canadian-aboriginal-syllabics-extended-a',
    name: '统一加拿大原住民音节文字扩展-A',
    type: 'range',
    ranges: [[0x11AB0, 0x11ABF]],
    total: 16,
  },
  {
    id: 'pau-cin-hau',
    name: '包钦豪文',
    type: 'range',
    ranges: [[0x11AC0, 0x11AFF]],
    total: 64,
  },
  {
    id: 'devanagari-extended-a',
    name: '天城文扩展-A',
    type: 'range',
    ranges: [[0x11B00, 0x11B5F]],
    total: 96,
  },
  {
    id: 'sharada-supplement',
    name: '夏拉达文补充',
    type: 'range',
    ranges: [[0x11B60, 0x11B7F]],
    total: 32,
  },
  {
    id: 'sunuwar',
    name: '苏努瓦尔文',
    type: 'range',
    ranges: [[0x11BC0, 0x11BFF]],
    total: 64,
  },
  {
    id: 'bhaiksuki',
    name: '拜克舒基文',
    type: 'range',
    ranges: [[0x11C00, 0x11C6F]],
    total: 112,
  },
  {
    id: 'marchen',
    name: '玛钦文',
    type: 'range',
    ranges: [[0x11C70, 0x11CBF]],
    total: 80,
  },
  {
    id: 'masaram-gondi',
    name: '玛萨拉姆贡德文字',
    type: 'range',
    ranges: [[0x11D00, 0x11D5F]],
    total: 96,
  },
  {
    id: 'gunjala-gondi',
    name: '贡贾拉贡德文字',
    type: 'range',
    ranges: [[0x11D60, 0x11DAF]],
    total: 80,
  },
  {
    id: 'tolong-siki',
    name: '托隆西基文',
    type: 'range',
    ranges: [[0x11DB0, 0x11DEF]],
    total: 64,
  },
  {
    id: 'makasar',
    name: '望加锡文',
    type: 'range',
    ranges: [[0x11EE0, 0x11EFF]],
    total: 32,
  },
  {
    id: 'kawi',
    name: '卡维文',
    type: 'range',
    ranges: [[0x11F00, 0x11F5F]],
    total: 96,
  },
  {
    id: 'lisu-supplement',
    name: '老傈僳文补充',
    type: 'range',
    ranges: [[0x11FB0, 0x11FBF]],
    total: 16,
  },
  {
    id: 'tamil-supplement',
    name: '泰米尔文补充',
    type: 'range',
    ranges: [[0x11FC0, 0x11FFF]],
    total: 64,
  },
  {
    id: 'cuneiform',
    name: '楔形文字',
    type: 'range',
    ranges: [[0x12000, 0x123FF]],
    total: 1024,
  },
  {
    id: 'cuneiform-numbers-and-punctuation',
    name: '楔形文字数字和标点',
    type: 'range',
    ranges: [[0x12400, 0x1247F]],
    total: 128,
  },
  {
    id: 'early-dynastic-cuneiform',
    name: '早期王朝楔形文字',
    type: 'range',
    ranges: [[0x12480, 0x1254F]],
    total: 208,
  },
  {
    id: 'cypro-minoan',
    name: '塞浦路斯-米诺斯文字',
    type: 'range',
    ranges: [[0x12F90, 0x12FFF]],
    total: 112,
  },
  {
    id: 'egyptian-hieroglyphs',
    name: '埃及圣书体',
    type: 'range',
    ranges: [[0x13000, 0x1342F]],
    total: 1072,
  },
  {
    id: 'egyptian-hieroglyph-format-controls',
    name: '埃及圣书体格式控制符',
    type: 'range',
    ranges: [[0x13430, 0x1345F]],
    total: 48,
  },
  {
    id: 'egyptian-hieroglyphs-extended-a',
    name: '埃及圣书体扩展-A',
    type: 'range',
    ranges: [[0x13460, 0x143FF]],
    total: 4000,
  },
  {
    id: 'anatolian-hieroglyphs',
    name: '安纳托利亚象形文字',
    type: 'range',
    ranges: [[0x14400, 0x1467F]],
    total: 640,
  },
  {
    id: 'gurung-khema',
    name: '古隆克玛文',
    type: 'range',
    ranges: [[0x16100, 0x1613F]],
    total: 64,
  },
  {
    id: 'bamum-supplement',
    name: '巴穆姆文补充',
    type: 'range',
    ranges: [[0x16800, 0x16A3F]],
    total: 576,
  },
  {
    id: 'mro',
    name: '默文',
    type: 'range',
    ranges: [[0x16A40, 0x16A6F]],
    total: 48,
  },
  {
    id: 'tangsa',
    name: '唐萨文',
    type: 'range',
    ranges: [[0x16A70, 0x16ACF]],
    total: 96,
  },
  {
    id: 'bassa-vah',
    name: '巴萨瓦文',
    type: 'range',
    ranges: [[0x16AD0, 0x16AFF]],
    total: 48,
  },
  {
    id: 'pahawh-hmong',
    name: '帕哈苗文',
    type: 'range',
    ranges: [[0x16B00, 0x16B8F]],
    total: 144,
  },
  {
    id: 'kirat-rai',
    name: '基拉特拉伊文字',
    type: 'range',
    ranges: [[0x16D40, 0x16D7F]],
    total: 64,
  },
  {
    id: 'medefaidrin',
    name: '梅德法伊德林文',
    type: 'range',
    ranges: [[0x16E40, 0x16E9F]],
    total: 96,
  },
  {
    id: 'beria-erfe',
    name: '贝利亚埃尔菲文',
    type: 'range',
    ranges: [[0x16EA0, 0x16EDF]],
    total: 64,
  },
  {
    id: 'miao',
    name: '柏格理苗文',
    type: 'range',
    ranges: [[0x16F00, 0x16F9F]],
    total: 160,
  },
  {
    id: 'ideographic-symbols-and-punctuation',
    name: '表意文字符号和标点',
    type: 'range',
    ranges: [[0x16FE0, 0x16FFF]],
    total: 32,
  },
  {
    id: 'tangut',
    name: '西夏文',
    type: 'range',
    ranges: [[0x17000, 0x187FF]],
    total: 6144,
  },
  {
    id: 'tangut-components',
    name: '西夏文部件',
    type: 'range',
    ranges: [[0x18800, 0x18AFF]],
    total: 768,
  },
  {
    id: 'khitan-small-script',
    name: '契丹小字',
    type: 'range',
    ranges: [[0x18B00, 0x18CFF]],
    total: 512,
  },
  {
    id: 'tangut-supplement',
    name: '西夏文补充',
    type: 'range',
    ranges: [[0x18D00, 0x18D7F]],
    total: 128,
  },
  {
    id: 'tangut-components-supplement',
    name: '西夏文部件补充',
    type: 'range',
    ranges: [[0x18D80, 0x18DFF]],
    total: 128,
  },
  {
    id: 'kana-extended-b',
    name: '假名扩展-B',
    type: 'range',
    ranges: [[0x1AFF0, 0x1AFFF]],
    total: 16,
  },
  {
    id: 'kana-supplement',
    name: '假名补充',
    type: 'range',
    ranges: [[0x1B000, 0x1B0FF]],
    total: 256,
  },
  {
    id: 'kana-extended-a',
    name: '假名扩展-A',
    type: 'range',
    ranges: [[0x1B100, 0x1B12F]],
    total: 48,
  },
  {
    id: 'small-kana-extension',
    name: '小假名扩展',
    type: 'range',
    ranges: [[0x1B130, 0x1B16F]],
    total: 64,
  },
  {
    id: 'nushu',
    name: '女书',
    type: 'range',
    ranges: [[0x1B170, 0x1B2FF]],
    total: 400,
  },
  {
    id: 'duployan',
    name: '杜普雷速记',
    type: 'range',
    ranges: [[0x1BC00, 0x1BC9F]],
    total: 160,
  },
  {
    id: 'shorthand-format-controls',
    name: '速记格式控制符',
    type: 'range',
    ranges: [[0x1BCA0, 0x1BCAF]],
    total: 16,
  },
  {
    id: 'symbols-for-legacy-computing-supplement',
    name: '以前计算时代的符号补充',
    type: 'range',
    ranges: [[0x1CC00, 0x1CEBF]],
    total: 704,
  },
  {
    id: 'miscellaneous-symbols-supplement',
    name: '杂项符号补充',
    type: 'range',
    ranges: [[0x1CEC0, 0x1CEFF]],
    total: 64,
  },
  {
    id: 'znamenny-musical-notation',
    name: '兹纳缅尼音乐符号',
    type: 'range',
    ranges: [[0x1CF00, 0x1CFCF]],
    total: 208,
  },
  {
    id: 'byzantine-musical-symbols',
    name: '拜占庭音乐符号',
    type: 'range',
    ranges: [[0x1D000, 0x1D0FF]],
    total: 256,
  },
  {
    id: 'musical-symbols',
    name: '音乐符号',
    type: 'range',
    ranges: [[0x1D100, 0x1D1FF]],
    total: 256,
  },
  {
    id: 'ancient-greek-musical-notation',
    name: '古希腊音乐记号',
    type: 'range',
    ranges: [[0x1D200, 0x1D24F]],
    total: 80,
  },
  {
    id: 'kaktovik-numerals',
    name: '卡克托维克数字',
    type: 'range',
    ranges: [[0x1D2C0, 0x1D2DF]],
    total: 32,
  },
  {
    id: 'mayan-numerals',
    name: '玛雅数字',
    type: 'range',
    ranges: [[0x1D2E0, 0x1D2FF]],
    total: 32,
  },
  {
    id: 'tai-xuan-jing-symbols',
    name: '太玄经符号',
    type: 'range',
    ranges: [[0x1D300, 0x1D35F]],
    total: 96,
  },
  {
    id: 'counting-rod-numerals',
    name: '算筹数字',
    type: 'range',
    ranges: [[0x1D360, 0x1D37F]],
    total: 32,
  },
  {
    id: 'mathematical-alphanumeric-symbols',
    name: '数学字母数字符号',
    type: 'range',
    ranges: [[0x1D400, 0x1D7FF]],
    total: 1024,
  },
  {
    id: 'sutton-signwriting',
    name: '萨顿-书写符号',
    type: 'range',
    ranges: [[0x1D800, 0x1DAAF]],
    total: 688,
  },
  {
    id: 'latin-extended-g',
    name: '拉丁字母扩展-G',
    type: 'range',
    ranges: [[0x1DF00, 0x1DFFF]],
    total: 256,
  },
  {
    id: 'glagolitic-supplement',
    name: '格拉哥里字母补充',
    type: 'range',
    ranges: [[0x1E000, 0x1E02F]],
    total: 48,
  },
  {
    id: 'cyrillic-extended-d',
    name: '西里尔字母扩展-D',
    type: 'range',
    ranges: [[0x1E030, 0x1E08F]],
    total: 96,
  },
  {
    id: 'nyiakeng-puachue-hmong',
    name: '创世纪苗文',
    type: 'range',
    ranges: [[0x1E100, 0x1E14F]],
    total: 80,
  },
  {
    id: 'toto',
    name: '托托文',
    type: 'range',
    ranges: [[0x1E290, 0x1E2BF]],
    total: 48,
  },
  {
    id: 'wancho',
    name: '万秋文',
    type: 'range',
    ranges: [[0x1E2C0, 0x1E2FF]],
    total: 64,
  },
  {
    id: 'nag-mundari',
    name: '纳格蒙达里文',
    type: 'range',
    ranges: [[0x1E4D0, 0x1E4FF]],
    total: 48,
  },
  {
    id: 'ol-onal',
    name: '奥尔欧纳尔文',
    type: 'range',
    ranges: [[0x1E5D0, 0x1E5FF]],
    total: 48,
  },
  {
    id: 'tai-yo',
    name: '傣幺文',
    type: 'range',
    ranges: [[0x1E6C0, 0x1E6FF]],
    total: 64,
  },
  {
    id: 'ethiopic-extended-b',
    name: '埃塞俄比亚字母扩展-B',
    type: 'range',
    ranges: [[0x1E7E0, 0x1E7FF]],
    total: 32,
  },
  {
    id: 'mende-kikakui',
    name: '门迪基卡库伊文',
    type: 'range',
    ranges: [[0x1E800, 0x1E8DF]],
    total: 224,
  },
  {
    id: 'adlam',
    name: '阿德拉姆字母',
    type: 'range',
    ranges: [[0x1E900, 0x1E95F]],
    total: 96,
  },
  {
    id: 'indic-siyaq-numbers',
    name: '印度西亚克数字',
    type: 'range',
    ranges: [[0x1EC70, 0x1ECBF]],
    total: 80,
  },
  {
    id: 'ottoman-siyaq-numbers',
    name: '奥斯曼西亚克数字',
    type: 'range',
    ranges: [[0x1ED00, 0x1ED4F]],
    total: 80,
  },
  {
    id: 'arabic-mathematical-alphabetic-symbols',
    name: '阿拉伯数学字母符号',
    type: 'range',
    ranges: [[0x1EE00, 0x1EEFF]],
    total: 256,
  },
  {
    id: 'mahjong-tiles',
    name: '麻将牌',
    type: 'range',
    ranges: [[0x1F000, 0x1F02F]],
    total: 48,
  },
  {
    id: 'domino-tiles',
    name: '多米诺骨牌',
    type: 'range',
    ranges: [[0x1F030, 0x1F09F]],
    total: 112,
  },
  {
    id: 'playing-cards',
    name: '扑克牌',
    type: 'range',
    ranges: [[0x1F0A0, 0x1F0FF]],
    total: 96,
  },
  {
    id: 'enclosed-alphanumeric-supplement',
    name: '带圈字母数字补充',
    type: 'range',
    ranges: [[0x1F100, 0x1F1FF]],
    total: 256,
  },
  {
    id: 'enclosed-ideographic-supplement',
    name: '带圈表意文字补充',
    type: 'range',
    ranges: [[0x1F200, 0x1F2FF]],
    total: 256,
  },
  {
    id: 'miscellaneous-symbols-and-pictographs',
    name: '杂项符号和图形',
    type: 'range',
    ranges: [[0x1F300, 0x1F5FF]],
    total: 768,
  },
  {
    id: 'emoticons',
    name: '表情符号',
    type: 'range',
    ranges: [[0x1F600, 0x1F64F]],
    total: 80,
  },
  {
    id: 'ornamental-dingbats',
    name: '装饰性图形符号',
    type: 'range',
    ranges: [[0x1F650, 0x1F67F]],
    total: 48,
  },
  {
    id: 'transport-and-map-symbols',
    name: '交通和地图符号',
    type: 'range',
    ranges: [[0x1F680, 0x1F6FF]],
    total: 128,
  },
  {
    id: 'alchemical-symbols',
    name: '炼金术符号',
    type: 'range',
    ranges: [[0x1F700, 0x1F77F]],
    total: 128,
  },
  {
    id: 'geometric-shapes-extended',
    name: '几何图形扩展',
    type: 'range',
    ranges: [[0x1F780, 0x1F7FF]],
    total: 128,
  },
  {
    id: 'supplemental-arrows-c',
    name: '补充箭头-C',
    type: 'range',
    ranges: [[0x1F800, 0x1F8FF]],
    total: 256,
  },
  {
    id: 'supplemental-symbols-and-pictographs',
    name: '补充符号和图形',
    type: 'range',
    ranges: [[0x1F900, 0x1F9FF]],
    total: 256,
  },
  {
    id: 'chess-symbols',
    name: '国际象棋符号',
    type: 'range',
    ranges: [[0x1FA00, 0x1FA6F]],
    total: 112,
  },
  {
    id: 'symbols-and-pictographs-extended-a',
    name: '符号和图形扩展-A',
    type: 'range',
    ranges: [[0x1FA70, 0x1FAFF]],
    total: 144,
  },
  {
    id: 'symbols-for-legacy-computing',
    name: '以前计算时代的符号',
    type: 'range',
    ranges: [[0x1FB00, 0x1FBFF]],
    total: 256,
  },
  {
    id: 'cjk-unified-ideographs-extension-b',
    name: 'CJK 扩展 B 区',
    type: 'range',
    ranges: [[0x20000, 0x2A6DF]],
    total: 42720,
  },
  {
    id: 'cjk-unified-ideographs-extension-c',
    name: 'CJK 扩展 C 区',
    type: 'range',
    ranges: [[0x2A700, 0x2B73F]],
    total: 4160,
  },
  {
    id: 'cjk-unified-ideographs-extension-d',
    name: 'CJK 扩展 D 区',
    type: 'range',
    ranges: [[0x2B740, 0x2B81F]],
    total: 224,
  },
  {
    id: 'cjk-unified-ideographs-extension-e',
    name: 'CJK 扩展 E 区',
    type: 'range',
    ranges: [[0x2B820, 0x2CEAF]],
    total: 5776,
  },
  {
    id: 'cjk-unified-ideographs-extension-f',
    name: 'CJK 扩展 F 区',
    type: 'range',
    ranges: [[0x2CEB0, 0x2EBEF]],
    total: 7488,
  },
  {
    id: 'cjk-unified-ideographs-extension-i',
    name: 'CJK 扩展 I 区',
    type: 'range',
    ranges: [[0x2EBF0, 0x2EE5F]],
    total: 624,
  },
  {
    id: 'cjk-compatibility-ideographs-supplement',
    name: '中日韩兼容表意文字补充',
    type: 'range',
    ranges: [[0x2F800, 0x2FA1F]],
    total: 544,
  },
  {
    id: 'cjk-unified-ideographs-extension-g',
    name: 'CJK 扩展 G 区',
    type: 'range',
    ranges: [[0x30000, 0x3134F]],
    total: 4944,
  },
  {
    id: 'cjk-unified-ideographs-extension-h',
    name: 'CJK 扩展 H 区',
    type: 'range',
    ranges: [[0x31350, 0x323AF]],
    total: 4192,
  },
  {
    id: 'cjk-unified-ideographs-extension-j',
    name: 'CJK 扩展 J 区',
    type: 'range',
    ranges: [[0x323B0, 0x3347F]],
    total: 4304,
  },
  {
    id: 'tags',
    name: '标签',
    type: 'range',
    ranges: [[0xE0000, 0xE007F]],
    total: 128,
  },
  {
    id: 'variation-selectors-supplement',
    name: '变体选择符补充',
    type: 'range',
    ranges: [[0xE0100, 0xE01EF]],
    total: 240,
  },
  {
    id: 'supplementary-private-use-area-a',
    name: '补充私人代用区-A',
    type: 'range',
    ranges: [[0xF0000, 0xFFFFF]],
    total: 65536,
  },
  {
    id: 'supplementary-private-use-area-b',
    name: '补充私人代用区-B',
    type: 'range',
    ranges: [[0x100000, 0x10FFFF]],
    total: 65536,
  }
];

export const STANDARD_BLOCKS: CharBlock[] = [
  {
    id: 'iso-8859-1',
    name: 'ISO-8859-1 (Latin-1)',
    type: 'range',
    ranges: [[0x0000, 0x00FF]],
    total: 256,
  },
  {
    id: 'iso-8859-5',
    name: 'ISO-8859-5 (Cyrillic)',
    type: 'range',
    ranges: [[0x0000, 0x007F], [0x00A0, 0x00A0], [0x0401, 0x045F]],
    total: 256,
  },
  {
    id: 'gb18030-level1',
    name: 'GB18030-2022 级别1',
    type: 'range',
    // 级别1包含 CJK统一汉字基本区（4E00-9FA5 及增补至 9FEF）和 扩展A区（3400-4DBF）。
    // 实际有效编码汉字为 27,533 个（并非全满）。这里采用全段范围以便网格展示，但总数记为标准规定的 27533。
    ranges: [[0x4E00, 0x9FFF], [0x3400, 0x4DBF]],
    total: 27533,
  },
  {
    id: 'gb18030-level2',
    name: 'GB18030-2022 级别2',
    type: 'range',
    // 级别2包含级别1的全部 27,533 字，外加《通用规范汉字表》中包含但未在级别1（基本区和扩A）中的 196 个生僻字。
    // 这196个字大多分布在扩展B区、C区、D区、E区和F区。总计：27533 + 196 = 27,729 个汉字。
    ranges: [[0x4E00, 0x9FFF], [0x3400, 0x4DBF]],
    extraChars: ["𬉼","𠳐","𥻗","𠙶","𬣙","𨙸","𬇕","𬣞","𬘓","𫭟","𫭢","𫇭","𫐄","𫵷","𣲘","𣲗","𬇙","𬣡","𫸩","𨚕","𫘜","𬘘","𫘝","𦭜","𬨂","𬀩","𬀪","𬬩","𫍣","𬣳","𬩽","𬮿","𬯀","𫰛","𬳵","𬳶","𫠊","𬍛","𬜬","𦰡","𪾢","𪨰","𫓧","𬬮","𬬱","𬬭","𦙶","𬘡","𬳽","𬘩","𫄧","𪟝","𬍤","𫭼","𬜯","𬂩","𫠆","𨐈","𬌗","𫑡","𪨶","𬬸","𬬻","𬬹","𬬿","𬭁","𫢸","𫗧","𬊈","𬒈","𨺙","𬳿","𫄨","𬘫","𫮃","𬱖","𬟽","𫓯","𫟹","𫟼","𠅤","𬇹","𬍡","𬤇","𫍯","𬤊","𫍲","𬯎","𬘬","𬘭","𬴂","𫘦","𫟅","𬘯","𫘧","𪣻","𡎚","𬃊","𬷕","𫐐","𬹼","𧿹","𫶇","𫖮","𬭊","𨱇","𫓶","𬭎","𫖯","𬱟","𫛭","𫷷","𬮱","𬊤","𣸣","𬴃","𫘨","𤧛","𬪩","𬒔","𬨎","𫐓","𫫇","𫓹","𬭚","𬭛","𬕂","𬶋","𬶍","𦝼","𫔶","𫌀","𫖳","𫘪","𫘬","𫞩","𡐓","𪤗","𣗋","𬸘","𬒗","𥔲","𫚖","𨱏","𬭤","𫚕","𬶐","𬶏","𩽾","𬸚","𬤝","𬙂","𬭩","𩾃","𬸣","𫍽","𬴊","𬞟","𥕢","𫟦","𬺈","𫠜","𪩘","𬭬","𨱑","𬭯","𫗴","𬸦","𫄷","𤩽","𬭳","𬭶","𫔍","𬭸","𨱔","𬭼","𫔎","𬸪","𬶟","𬶠","𬶨","𦈡","𫄸","𬟁","𥖨","𦒍","𬙊","𬶭","𩾌","𨟠","𬶮","𨭉","𬙋","𤫉","𬺓","𫚭"],
    total: 27729,
  },
  {
    id: 'gb18030-level3',
    name: 'GB18030-2022 级别3',
    type: 'range',
    // 级别3支持了GB18030-2022规定的全部汉字，总数为 87,887 个，外加 214 个康熙部首。
    // 它覆盖了CJK基本区以及扩展A到扩展F区的所有汉字，以及康熙部首区块。
    ranges: [
      [0x4E00, 0x9FFF], // 基本区
      [0x3400, 0x4DBF], // 扩展 A
      [0x20000, 0x2A6DF], // 扩展 B
      [0x2A700, 0x2B73F], // 扩展 C
      [0x2B740, 0x2B81F], // 扩展 D
      [0x2B820, 0x2CEAF], // 扩展 E
      [0x2CEB0, 0x2EBEF], // 扩展 F
      [0x2F00, 0x2FD5]    // 康熙部首 (Kangxi Radicals)
    ],
    total: 88101,
  },
  {
    id: 'gb2312',
    name: 'GB2312 (简)',
    type: 'list',
    list: GB2312_CHARS,
    total: 6763,
  },
  {
    id: 'big5',
    name: 'BIG5 (繁)',
    type: 'list',
    list: BIG5_CHARS,
    total: 13461,
  },
  {
    id: 'joyo-kanji',
    name: '日本常用汉字 (Joyo)',
    type: 'list',
    list: JOYO_KANJI,
    total: [...JOYO_KANJI].length,
  },
  {
    id: 'jis-x-0208-level1',
    name: 'JIS X 0208 第一水准',
    type: 'list',
    list: JIS_LEVEL1_CHARS,
    total: [...JIS_LEVEL1_CHARS].length,
  },
  {
    id: 'jis-x-0208-level2',
    name: 'JIS X 0208 第二水准',
    type: 'list',
    list: JIS_LEVEL2_CHARS,
    total: [...JIS_LEVEL2_CHARS].length,
  },
  {
    id: 'ks-x-1001',
    name: 'KS X 1001',
    type: 'list',
    list: KSX1001_HANGUL,
    total: [...KSX1001_HANGUL].length,
  },
  {
    id: 'japanese-kana',
    name: '假名',
    type: 'range',
    ranges: [[0x3040, 0x309F], [0x30A0, 0x30FF]],
    total: 189,
  }
];

const blockCache = new Map<string, string[]>();

export function getCharsForBlock(block: CharBlock): string[] {
  if (blockCache.has(block.id)) {
    return blockCache.get(block.id)!;
  }
  
  let chars: string[] = [];
  if (block.type === 'range' && block.ranges) {
    for (const [start, end] of block.ranges) {
      for (let i = start; i <= end; i++) {
        try {
          chars.push(String.fromCodePoint(i));
        } catch (e) {
          // ignore invalid code points
        }
      }
    }
  } else if (block.type === 'list' && block.list) {
    chars = Array.from(block.list);
  }
  
  if (block.extraChars) {
    chars = chars.concat(block.extraChars);
  }
  
  blockCache.set(block.id, chars);
  return chars;
}

export function getUnicodeBlockForChar(char: string): string {
  const code = char.codePointAt(0);
  if (!code) return "Unknown";
  
  for (const block of UNICODE_BLOCKS) {
    if (block.type === 'range' && block.ranges) {
      for (const [start, end] of block.ranges) {
        if (code >= start && code <= end) {
          return block.name;
        }
      }
    }
  }
  return "Unknown Block";
}
